### ISSUE TITLE
Fix docstrings

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#100]
Particularly in utils and applications.

**Comment by adpartin** [comment]
I suggest exploring LLM to across the repo and then refine manually. @jonesse3 would you like to explore this?

**Comment by adpartin** [comment]
@jonesse3 I suggest to close this. I suggest creating an issue per file to fix style (including docstrings).

**Comment by adpartin** [comment]
@jonesse3 I suggest creating an issue per file to fix style (including docstrings).
