### ISSUE TITLE
cuda name

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#106]
a lot of these models have cuda_name or similar -- is there any reason we might want that as an improvelib param – Alex says env variable

**Comment by wilke** [comment]
This should have the same mechanic as input and output directory.

- repect env CUDA_VISIBLE_DEVICES
- allow for defining it on the command line and setting the env variable
- default for the cli is , getenv(CUDA_VISIBLE_DEVICE , 0)

- option name is gpu_id (!?)

**Comment by adpartin** [comment]
@wilke has this been resolved?

**Comment by adpartin** [comment]
Addressed in PR #107
