### ISSUE TITLE
Test data format for list of GPUs in CSA workflow

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#108]
There should be a test for the format

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/IMPROVE/pull/107#discussion_r1750931308_

**Comment by adpartin** [comment]
@wilke do you mean we need a test that check that the `params['available_accelerators']` is valid?

**Comment by priyanka9991** [comment]
The 'available_accelerators' parameters has been defined with an "nargs":"+" option, allowing it to be a list.
https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/priyanka/fixes/workflows/parsl_csa/csa_params_def.py

@wilke Do you mean we need specific tests to check this?

**Comment by adpartin** [comment]
Not relevant anymore.
