### ISSUE TITLE
Use csa specifc config or base config 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#109]
Let's switch to the base config.

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/IMPROVE/pull/107#discussion_r1750930493_

**Comment by adpartin** [comment]
@wilke I tried that at some point, but it didn't work. See my comment here:

https://github.com/JDACS4C-IMPROVE/GraphDRP/blob/develop/csa_wf.py#L54
