### ISSUE TITLE
Please update the requirements file with actual requirements and not a conda dump.

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#115]
Please update the requirements file with actual requirements and not a conda dump.

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/IMPROVE/pull/114#pullrequestreview-2293717909_

**Comment by jonesse3** [comment]
We possibly don't need this file. I got it to work doing the following:
```
conda create -n parsl parsl -y
conda activate parsl 
```

**Comment by nkoussa** [comment]
conda create -n parsl parsl numpy pandas scikit-learn pyyaml -y

**Comment by jonesse3** [comment]
If we want to start using improvelib from PyPi, we can do the following:
```
conda create -n parsl parsl python==3.7 -y
conda activate parsl
pip install improvelib
```
Otherwise, what Natasha wrote above includes what we need to install to run improvelib from the IMPROVE repo.

**Comment by adpartin** [comment]
> conda create -n parsl parsl numpy pandas scikit-learn pyyaml -y

@priyanka9991 We should add this to this README https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/workflows/parsl_csa

**Comment by jonesse3** [comment]
Should we delete this file, https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/parsl_csa/parsl_env.yml, or have a cleaner version?

**Comment by priyanka9991** [comment]
Good catch. Yes we should delete it.

**Comment by jonesse3** [comment]
Issue completed
