### ISSUE TITLE
do we need to download csa data here

### ISSUE THREAD

**Issue by adpartin** [JDACS4C-IMPROVE/IMPROVE#126]
do we need to download csa data in setup_improve.sh that resides in the IMPROVE repo? How this exactly used?
https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/setup_improve.sh

**Comment by nkoussa** [comment]
I don't know why this is here

**Comment by adpartin** [comment]
> I don't know why this is here

@nkoussa you agree it should not download the csa data?

**Comment by nkoussa** [comment]
Yeah I agree. It looks like you put that file there 2 months ago? Maybe as a template or an overzealous commit? But yeah, I can't think of a reason it should be there, we can put it a setup_improve and download_csa in templates if we want.

**Comment by adpartin** [comment]
Solved PR #143.
