### ISSUE TITLE
readme for csa scores

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#132]
post_process/cross_study/csa_postproc.py

not 

post_process/csa/csa_postproc.py

also very confusing since there's workflow_utils directory too

**Comment by nkoussa** [comment]
here I mean, btw:
https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/post_process/cross_study

**Comment by adpartin** [comment]
@nkoussa this is a good point related to scripts organization within the repo. The discussion is about the following:

- The workflows are here: https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/workflows
- Post-processing scripts, which I believe will include scripts related to specific evaluation schemes (currently include only cross-study), are here: https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/post_process
- Additional utils specific to evaluation schemes: https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/improvelib/workflow_utils

I think it makes more sense to put _everything_ (workflow execution scripts, post-processing scripts, all relevant utils), inside a specific the specific workflow dir (e.g., https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/workflows/parsl_csa). But in this case, we want to use the same post-processing in bruteforce and parsl.
It maybe makes more sense to put all files related to
