### ISSUE TITLE
Template for setup_improve.sh

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/IMPROVE#152]
@adpartin @nkoussa @jonesse3 It will be useful to add a template or an example for setup_improve.sh here to help new users.
https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/templates

**Comment by nkoussa** [comment]
Good point, I can do that.

**Comment by adpartin** [comment]
Solved in #154
