### ISSUE TITLE
'Config' object has no attribute 'dict'

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/IMPROVE#19]
https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/reference-implementation-csa/improve/CSA/Config/Common.py

  "improve/CSA/Config/Common.py", line 167, in initialize_parameters
    return self.dict()
AttributeError: 'Config' object has no attribute 'dict'

**Comment by jonesse3** [comment]
Does this still need to be fixed?

**Comment by priyanka9991** [comment]
No. This was an issue in the initial version of IMPROVE. We can close this issue.
