### ISSUE TITLE
Precedence of config_file parameters over default parameters

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/IMPROVE#22]
initialize_parameters() function does not consider the precedence of config_file parameters over default parameters.

https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/reference-implementation-csa/improve/CSA/Config/Common.py

**Comment by wilke** [comment]
depends on #43

**Comment by wilke** [comment]
Solved and tested with GraphDRP by @priyanka9991 

Code pre-reads config file and sets command line defaults to the values from config file.
