### ISSUE TITLE
Round decimal

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/IMPROVE#4]
Please add a round decimal for true_col_name to avoid an assertion error:

```
df = mm.round({params["y_col_name"]: round_decimals,
                       true_col_name: round_decimals,
                       pred_col_name: round_decimals})
```

https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/d194934e2259e5edf85073e6cb72e790be458d18/improve/framework.py#L494

**Comment by wilke** [comment]
@jonesse3 Could you please check if this has been addressed?

**Comment by jonesse3** [comment]
No it hasn't been addressed. Let me know if I should create a branch to fix this.

**Comment by wilke** [comment]
Yes, please.

On Jan 29, 2024, at 1:15 PM, Sara Jones ***@***.***> wrote:



No it hasn't been addressed. Let me know if I should create a branch to fix this.

**Comment by jonesse3** [comment]
I reviewed the changes Alex made to address the assertion error with adding the rounding of the decimals. This fixes this issue.
