### ISSUE TITLE
rmse fails with scikitlearn v0.21.2

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#41]
Probably other older ones as well, no "squared", see here: 
https://scikit-learn.org/0.18/modules/generated/sklearn.metrics.mean_squared_error.html

**Comment by jonesse3** [comment]
It seems that v.0.21x and below are affected: https://stackoverflow.com/questions/17197492/is-there-a-library-function-for-root-mean-square-error-rmse-in-python.

**Comment by jonesse3** [comment]
Can check that this works with IGTD once it's updated to work with the new version of improvelib. Need two other models for the other versions to complete testing.

**Comment by jonesse3** [comment]
The pip package of improvelib installs scikit-learn. Will need to check this doesn't cause any downstream package conflicts if included.

**Comment by wilke** [comment]
@jonesse3 Is this fixed?

**Comment by nkoussa** [comment]
@wilke In theory, yes but I can't test it until IGTD gets updated and tested.

**Comment by nkoussa** [comment]
works
