### ISSUE TITLE
Conflict of types when parameters read in via config or cli 

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/IMPROVE#43]
Currently, config and cli values are read in as string type. @adpartin added a function` cast_value` in `improvelib/utils.py`. See commit of the fix: https://github.com/JDACS4C-IMPROVE/IMPROVE/commit/4c2aacc4bf850bdba100f069b0a53216d81e257e. @priyanka9991 observed a similar issue with list types.

@wilke Is there another efficient way to check types?

I can add a unit test to check types for different parameters when read in as default, config, or cli.

**Comment by wilke** [comment]
This problem can be solved by partially reading the command line options and checking for a config file. Then override the default values in the CLI with the values from the config file and re-read all command line options.

**Comment by jonesse3** [comment]
Related to this issue is that parameters must include default, otherwise one gets a not defined error. Either this can be addressed in the code or must be clearly stated in the user guide. What do you want as expected behavior @nkoussa , @adpartin, @wilke ?

**Comment by nkoussa** [comment]
Currently it should give this warning:

self.logger.warning(
                        "Found %s in options. This option is predefined and can not be overwritten.", o)
                    self.logger.debug("Removing %s from options", o)

I think at minimum the warning should be more explicit that it's predefined with a different default. Like "Found %s as a parameter defined in the model, but this is predefined and can not be overwritten. The default value provided by the model will not be used, instead the default is defined by improvelib." or something to that effect, Sara you could probably word it better.

**Comment by wilke** [comment]
Types are preserved now by seeding defaults with values from a config file.
