### ISSUE TITLE
Unit test for initialize paramters 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#44]
https://github.com/JDACS4C-IMPROVE/IMPROVE/issues/43#issue-2470439664

Only check for types for standard input parameters. I would consider additional_definitions not under our control initially.

**Comment by jonesse3** [comment]
Completed here: https://github.com/JDACS4C-IMPROVE/IMPROVE/pull/50

Checked for boolean, string, integer, float, and list types for CLI and config files. Used additional_definitions to check types.
