### ISSUE TITLE
Documentation for initialze_parameters 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#45]
Create specification and use case example for initialize_parameters , add to code base and documentation.

**Comment by adpartin** [comment]
@wilke Does this ticket requests to update the docs repo and this repo?

**Comment by wilke** [comment]
Example code and readme should be in the IMPROVE repo,  examples and documentation in the docs repo, e.g. quickstart, curator section or cookbook.

**Comment by nkoussa** [comment]
@wilke Where in the IMPROVE repo? It's in docs and I'm making templates in the IMPROVE repo now

**Comment by wilke** [comment]
Create a directory called templates.

**Comment by nkoussa** [comment]
There's already a directory called templates, I'm just fixing them there
