### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by rajeeja** [JDACS4C-IMPROVE/IMPROVE#47]
LGBM testing IMPROVE

**Comment by wilke** [comment]
What is this ticket about?

**Comment by rajeeja** [comment]
As the description says it is to test the library with LGBM with GitHub actions

**Comment by wilke** [comment]
LGBM is not part of this repo. I prefer to test it with the provided unittests.

**Comment by adpartin** [comment]
Not sure if it should be here, so I'm closing this for now. We can re-open if need to.
