### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by rajeeja** [JDACS4C-IMPROVE/IMPROVE#48]
make a conda installable package for IMPROVE

**Comment by wilke** [comment]
@rajeeja  What is the advantage of a conda package over a pypy package, which is easy to install with pip? Conda is not on the critical path yet.

**Comment by adpartin** [comment]
@wilke @rajeeja It would be nice to have pip and Conda installations available in the future. But at this point, we should not spend any time on conda. Let's just focus on pip installation.

**Comment by nkoussa** [comment]
Conda is apparently starting to charge academic users and people are moving away from conda, we should probably have environment instructions for the models as venvs too.

**Comment by adpartin** [comment]
@wilke @rajeeja @nkoussa It's not on the critical path. Let's clean the Issues.

**Comment by jonesse3** [comment]
Yeah that's fine. Just wondering for the singularity containers, we should probably not use conda. I don't know if we violate some license agreement if we containerize it.
