### ISSUE TITLE
Create legacy tag for develop

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#53]
1. Create tag
2.  Example how to checkout code for this tag
3. merge framework-api into develop

**Comment by wilke** [comment]
New tag is [v0.0.3-beta](https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/v0.0.3-beta)

**Comment by wilke** [comment]
Cloning single tag/branch:
`git clone <repo_url> --branch v0.0.3-beta --single-branch`

**Comment by wilke** [comment]
@ jonesse3 We should make a pip release for this code, too.

**Comment by nkoussa** [comment]
@adpartin @wilke I'm testing this now FYI

**Comment by nkoussa** [comment]
@adpartin @wilke This works, `git checkout v0.0.3-beta` also works. We should make sure the model repos get a branch named v0.0.3-beta as well with the version of the model that works with the legacy version of IMPROVE.

**Comment by adpartin** [comment]
> @adpartin @wilke This works, `git checkout v0.0.3-beta` also works. We should make sure the model repos get a branch named v0.0.3-beta as well with the version of the model that works with the legacy version of IMPROVE.

@nkoussa I think tag should work as well. Right?
