### ISSUE TITLE
CANDLE checkpointing conflicts with current IMPROVE cross-study workflow setup

### ISSUE THREAD

**Issue by AlexandrNP** [JDACS4C-IMPROVE/IMPROVE#6]
According to the latest candlezation requirements, the checkpointing path is managed by the CANDLE library:

```
ckpt = candle.CandleCkptPyTorch(vars(self.args))
ckpt.set_model({"model": self.model, "optimizer": opt})
...
ckpt.ckpt_epoch(epo, float(train_loss))
```

During cross-study runs, model checkpointing defaults to the same directory, preventing training different models, as the training procedure restarts from the same checkpoint.

**Comment by adpartin** [comment]
This is not relevant, since candle is not a dependency in improvelib at this point.
