### ISSUE TITLE
Rename test directory to Tests

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#62]
The name "test" is overloaded in unix, it is also a shell command. Common examples use Tests or tests.

**Comment by jonesse3** [comment]
I created a folder called `tests` with the unittests. Can move over the other files not currently in there and then delete `test`. We really need to clean up any unused code.

**Comment by wilke** [comment]
@jonesse3 Can you do that and delete unused fand undocumented files?

**Comment by wilke** [comment]
Depends on #67 and has been resolved. We agreed on `tests`.
