### ISSUE TITLE
Decide what to do with model-specific data

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#68]
@adpartin @priyanka9991 @jonesse3 We need to decide what to do with model-specific data (i.e. supp_data). I don't like the idea of putting anything in the csa_data folder, but any decision is better than no decision.

**Comment by jonesse3** [comment]
If it's a shared resource, would be nice to add a folder for supplemental data. If it's specific to the model, I think it's fine to keep within the model's repository (assuming file size is not an issue).

**Comment by nkoussa** [comment]
Agreed, I think we should look at what these are and if there are common ones (KEGG pathways, miRNA, something like that) it should be in the standardized benchmark dataset.

**Comment by priyanka9991** [comment]
I had implemented something for Paccmann as it needs model specific data. I defined 3 parameters in the config file:
model_specific_data - 'True' if model needs model specific data
model_specific_outdir - Directory to store model specific data
model_specific_data_url - FTP link that contains the data.
I also have a bash script: model_specific_data_download.sh, that downloads the data and stores it.
Here is the implementation (lines 357 to 365): https://github.com/JDACS4C-IMPROVE/Paccmann_MCA/blob/Parsl/workflow_csa.py

```
if params['model_specific_data']:
    auth_data_download = ["bash",
        "model_specific_data_download.sh",
        str(params['model_specific_data_url']),
        str(params['model_specific_outdir'])
    ]
    result = subprocess.run(auth_data_download, capture_output=True,
                            text=True, check=True)

**Comment by priyanka9991** [comment]
Another solution will be to include the model specific data download within the setup script that GraphDRP has:
https://github.com/JDACS4C-IMPROVE/GraphDRP/blob/framework-api/setup_improve.sh
Then within the model script we need to have parameters 'model_specific_data' and 'model_specific_outdir '.

**Comment by nkoussa** [comment]
@priyanka9991 @wilke @adpartin Just to confirm on this issue, the plan is to have in improvelib's preprocess arguments a --supplemental-data-dir that defaults to None, correct?

**Comment by adpartin** [comment]
Something like that. I'll reach out to Priyanka to discuss this.
