### ISSUE TITLE
Name change not propagated to models, e.g. GRaphDRP

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#84]
https://github.com/JDACS4C-IMPROVE/IMPROVE/blame/45196f799de6053ed598b215899f8cc86bbef235/improvelib/initializer/cli_params_def.py#L233

Should be moved to GraphDRP

**Comment by priyanka9991** [comment]
Refactored the parameter 'test_batch' to 'infer_batch' in GraphDRP to comply with the new parameter names in IMPROVE lib.
