### ISSUE TITLE
hard code and deprecate y_data_suffix

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#85]
# TODO y_data_suffix is currently used in utils.py (previously framework.py)
        # We plan to hard-code this in the future release and deprecate. 
        {"name": "y_data_suffix", # default expected
         "type": str,
         "default": "y_data", # TODO Oleksandr: "gives error when default is not set"
         "help": "[Dep] Suffix to compose file name for storing true y dataframe."
         },

**Comment by nkoussa** [comment]
also this in cli_param_def

 # TODO y_data_preds_suffix, json_scores_suffix, pred_col_name_suffix
    # are currently used in utils.py (previously framework.py)
    # We plan to hard-code these in the future release and deprecate.
    # Defined in improve_train_conf and improve_infer_conf
    {"name": "y_data_preds_suffix", # default expected
     "type": str,
     "default": "predicted",
     "help": "[Dep] Suffix to use for file name that stores predictions."
    },
    {"name": "json_scores_suffix", # default expected
     "type": str,
     "default": "scores",
     "help": "[Dep] Suffix to use for file name that stores scores."
    },
    {"name": "pred_col_name_suffix", # default expected
     "type": str,
     "default": "_pred",
     "help": "[Dep] Suffix to add to a column name in the y data file to identify \
             predictions made by the model (e.g., if y_col_name is 'auc', then \
             a new column that stores model predictions will be added to the y \
             data file and will be called 'auc_pred')."

**Comment by adpartin** [comment]
PR approved

**Comment by adpartin** [comment]
PR approved

**Comment by adpartin** [comment]
PR approved
