### ISSUE TITLE
local variable 'mm' referenced before assignment

### ISSUE THREAD

**Issue by Liuy12** [JDACS4C-IMPROVE/IMPROVE#9]
This is a bug in framework.py, line 512, ‘mm’ needs to be defined first before referenced.

**Comment by adpartin** [comment]
@Liuy12 Good call. I just fixed it. But it's weird that you encounter this problem because if you run preprocessing, you should have val_y_data.csv file available to load.

**Comment by adpartin** [comment]
Fixed
