### ISSUE TITLE
do we need this requirements.txt in the repo?

### ISSUE THREAD

**Issue by adpartin** [JDACS4C-IMPROVE/IMPROVE#90]
Do we need this requirements.txt?
https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/requirements.txt
I'm surprised it contains torch and tensorflow.

**Comment by wilke** [comment]
We need one, but it should be updated to meet the current requirements.

**Comment by adpartin** [comment]
@wilke I can update requirement.txt with what we have in `https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/pyproject.toml`. Does it make sense?

**Comment by wilke** [comment]
yes, I think so.

**Comment by adpartin** [comment]
Let's wait for @jonesse3 to do it since she might update pyproject.toml

**Comment by jonesse3** [comment]
I don't need to update the pyproject.toml unless @rajeeja thinks it needs to be modified. The dependencies in the toml file shouldn't have to change.

**Comment by adpartin** [comment]
We'll need to specify python package version numbers in toml file and update requirements.txt.

**Comment by jonesse3** [comment]
I updated requirements.txt. For now, no version numbers are specified.
