### ISSUE TITLE
Remove default_model variable - not used

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IMPROVE#96]
https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/7bdc917e9b7c68e06ec4458e834c06a06b60b326/improvelib/initializer/config.py#L635

**Comment by nkoussa** [comment]
@wilke Do you want me to take this out?

**Comment by wilke** [comment]
> @wilke Do you want me to take this out?

ok, assigned the issue to you.

**Comment by nkoussa** [comment]
will do in the morning
