### ISSUE TITLE
Take environment variables out

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#98]
As I understand, we don't want the models to use env variables anymore (e.g. IMPROVE_DATA_DIR)

**Comment by nkoussa** [comment]
@wilke @adpartin Do we want these out or leave them in?

**Comment by wilke** [comment]
We want to leave these in. The code is setting them and external codes relay on it.

**Comment by nkoussa** [comment]
Ah ok.
