### ISSUE TITLE
Do we want to not pass params to these functions?

### ISSUE THREAD

**Issue by nkoussa** [JDACS4C-IMPROVE/IMPROVE#99]
@adpartin @wilke I can do this and/or close the issue if you guys let me know what you prefer

These functions (in utils) still take params
build_ml_data_name(params: Dict, stage: str) 
and 
build_model_path(params: Dict, model_dir: Union[Path, str])  
and 
save_stage_ydf(ydf: pd.DataFrame, params: Dict, stage: str)

**Comment by wilke** [comment]
if these functions are in utils (stand alone) I prefer not to use params but to be explicit. This is only important if we expose this functions to model developers but consistency would be nice in any case.

**Comment by adpartin** [comment]
@wilke @nkoussa we should try to avoid passing params. But I think we should first "merge" framework-api to develop and keep working in develop.

**Comment by nkoussa** [comment]
OK will do tomorrow. @adpartin Merge in GraphDRP and LGBM you mean?

**Comment by adpartin** [comment]
> OK will do tomorrow. @adpartin Merge in GraphDRP and LGBM you mean?

Yes. I meant after we merge both LGBM and GraphDRP to develop. Then we can implement the changes you mentioned in IMPROVE lib and the models.
